### ISSUE TITLE
模态框溢出问题

### ISSUE THREAD

**Issue by Tinhone** [Jannchie/roku-ui#2]
`当换行过多时，文本框会溢出模态框并且遮挡住评论。`

![图片](https://user-images.githubusercontent.com/81268244/198905988-058e8315-fe40-42f4-bfbc-beb8a5fe0c30.png)
![图片](https://user-images.githubusercontent.com/81268244/198905997-43d52087-0cdc-470b-b370-28861aefa25c.png)
![图片](https://user-images.githubusercontent.com/81268244/198906007-0fa5eb2a-1d99-4c7e-9fd9-98dcc9a88944.png)
以上截图自 Google Chrome V105

_Firefox V88 还出现了背景没有模糊的情况，不知道最新版会不会出现，在这里也提一下_

**Comment by Jannchie** [comment]
原来如此，居然是这么多空格的情况嘛，我会增加一个行数上限的限制。

> Firefox V88 还出现了背景没有模糊的情况，不知道最新版会不会出现，在这里也提一下

我使用的 Firefox 已经是 106 版本了。不会有背景没有模糊的情况，这边暂时不会对远古浏览器进行兼容。

**Comment by Tinhone** [comment]
<p>大大辛苦了！(*^▽^*)</p>
